import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
          <NavBar></NavBar>
          <main className="ms-[58px]">{children}</main>
      </body>
    </html>
  );
}
